### ISSUE TITLE
Adding multiple RSS feed wigets?

### ISSUE THREAD

**Issue by poVoq** [q2a-projects/Q2A-Ultimate-Widgets#1]
I would like to have different RSS feed widgets for different pages in the side bar.

I guess it is an unavoidable limitation that you can't have more than one of the same kind of widget at "top of sidebar" etc.?

But the real problem seems to be that only the first RSS feed actually works. If I add another the widget and title is shown fine, but it doesn't seem to fetch the other RSS feed.

**Comment by TohidN** [comment]
I've just tested the RSS Feed widget with rss feeds from three different sites and it showed all of them. maybe the second rss feed you entered could not be fetched or parsed?

And yes, the limitation regarding number of widget of same type in each position exists. While we're using Q2A's own admin form to process widget options, this issue can't be helped. If I find some free time to create a brand new widget system for this plugin, I'll solve Q2A's limitations in this regard. but with the pile of job and personal projects in the way it's unlikely to happen.

**Comment by poVoq** [comment]
You seem to be correct.
Any idea why a standard dokuwiki feed will not work?

Ok found out: RSS2.0 works, ATOM1.0 not.
